# Cloud Build configuration for deploying to Cloud Run
# This file is used when deploying via: gcloud builds submit

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'architecture-kb-orchestrator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--update-secrets'
      - 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
      - '--update-secrets'
      - 'GITHUB_TOKEN=github-token:latest'
      - '--update-secrets'
      - 'WEBHOOK_URL=webhook-url:latest'
      - '--labels'
      - 'application=dependency-orchestrator,environment=production,managed-by=cloud-build,component=orchestration,a2a-enabled=true'

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Tags for cost tracking (Cloud Build uses tags, not labels)
tags:
  - 'dependency-orchestrator'
  - 'production'
  - 'orchestration'

timeout: '1200s'
