# Cloud Build configuration for Terraform-managed deployments
# This config ONLY builds and pushes images - Terraform handles deployment

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:${_COMMIT_SHA}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'
      - '.'

  # Push the container image to Container Registry (with commit SHA)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:${_COMMIT_SHA}'

  # Push the container image to Container Registry (latest tag)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'

# Substitution variables with defaults
substitutions:
  _COMMIT_SHA: 'latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:${_COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/architecture-kb-orchestrator:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Tags for cost tracking (Cloud Build uses tags, not labels)
tags:
  - 'dependency-orchestrator'
  - 'terraform-managed'
  - 'build-only'

timeout: '1200s'
